lesovod/lesovod/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from lesovod.views import about, employers, index
from posts.views import new_post, posts

appname = 'lesovod'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('employers/', employers, name='employers'),
    path('posts/', posts, name='posts'),
    path('new_post/', new_post, name='new_post'),
]
if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

lesovod/users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

app_name = 'users'

urlpatterns = [
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
]

lesovod/employers/models.py
from django.db import models


class Employers(models.Model):
    position = models.CharField(
        help_text='Должность',
        verbose_name='Должность',
        max_length=50,
    )
    name = models.CharField(
        help_text='Имя и Фамилия',
        verbose_name='Имя и Фамилия',
        max_length=50,
    )
    work_since = models.DateTimeField(
        help_text='Дата устройства в компани.',
        verbose_name='Устроился  в компанию',
        auto_now_add=False,
        null=True,
        blank=True
    )
    description = models.TextField(
        help_text='О сотруднике',
        verbose_name='О сотруднике',
        null=True,
        blank=True,
    )
    image = models.ImageField(
        help_text='Фото сотрудника',
        verbose_name='Фото сотрудника',
        upload_to='images/employers',
        null=True,
        blank=True,

    )

    def __str__(self) -> str:
        return str(self.description)

lesovod/posts/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class Post(models.Model):
    title = models.CharField(
        max_length=50,
        null=True,
        blank=True,
    )
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
    )
    image = models.ImageField(
        upload_to='images/',
        blank=True,
        null=True,
    )

    def __str__(self) -> str:
        return str(self.text)

lesovod/posts/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = (
            'title',
            'text',
            'image',
        )

lesovod/users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

lesovod/core/views.py
from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'core/404.html', {'path': request.path}, status=404)


def server_error(request):
    return render(request, 'core/500.html', status=500)


def permission_denied(request, exception):
    return render(request, 'core/403.html', status=403)


def csrf_failure(request, reason=''):
    return render(request, 'core/403csrf.html')

lesovod/lesovod/views.py
from django.shortcuts import render

from employers.models import Employers
from posts.models import Post


def index(request):
    template = 'index.html'
    title = 'Главная страница'
    context = {
        'title': title,
    }
    return render(request, template, context)


def about(request):
    template = 'about.html'
    title = 'О компании'
    context = {
        'title': title,
    }
    return render(request, template, context)


def employers(request):
    template = 'employers.html'
    employers = Employers.objects.all()
    title = 'Сотрудники'
    context = {
        'title': title,
        'employers': employers,
    }
    return render(request, template, context)


def posts(request):
    template = 'posts.html'
    title = 'Блог'
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'title': title,
        'posts': posts,
    }
    return render(request, template, context)

lesovod/posts/views.py
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.forms.utils import to_current_timezone
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt

from posts.forms import PostForm
from posts.models import Post


def posts(request):
    title = 'Блог'
    template = 'posts.html'
    post_list = Post.objects.all().order_by('-pub_date')
    paginator = Paginator(post_list, 4)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
        'title': title,
    }
    return render(request, template, context)


@csrf_exempt
@login_required
def new_post(request):
    title = 'Новый пост'
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
    )
    if not form.is_valid():
        return render(request, 'new_post.html', {
            'form': form, 'title': title}
        )
    post = form.save(commit=False)
    post.author = request.user
    post.pub_date = to_current_timezone
    post.save()
    return redirect('posts')

lesovod/templates/about.html
{% extends 'base.html' %} {% block content %}
<main>
  <div class="jumbotron jumbotron-fluid bg-transparent text-white">
    <div class="container">
      <h1 class="display-4">О компании</h1>
      <p class="lead">История компании, основная деятельность, идеи, цели.</p>
    </div>
  </div>
</main>
{% endblock %}

lesovod/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>{{title}}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" 
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
          crossorigin="anonymous">
    <link rel="stylesheet" href={% static 'css/style.css' %}>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" />
    <meta charset="utf-8">
    <meta name="description" content="Лесовод">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'icons/icon.png' %}">
  </head>
    <header>
    {%include 'includes/header.html' %}
    </header>
    <body>
      <div id="wrapper">
        <main>
          {% block content %}
          'Контент не подвезли'
          {% endblock %}
        </main>
      </div>
  </body>
      <footer>
        {% include 'includes/footer.html' %}
      </footer>
</html>

lesovod/templates/employers.html
{% extends 'base.html' %} {% load thumbnail %} {% block content %}
<section class='employer'>
{% for employer in employers %}
    <div class="employer-card">
        {% thumbnail employer.image '360' as im %}
            <img src="{{ im.url }}" class="employer-photo" alt="Фото сотрудника">
        {% endthumbnail %}
        <h5 class="employer-text">{{ employer.name }}</h5>
        <h1 class='employer-text'>{{ employer.position }}</h1>
    </div>
{% endfor %}
</section>
{% endblock %}

lesovod/templates/employers1.html
{% extends 'base.html' %} {% load thumbnail %} {% block content %}
<main>
  <div class="card-deck">
    {% for employer in employers %}
    <div class="card">
    {% thumbnail employer.image 'x360' as im %}
        <img class="card-img-top" src="{{ im.url }}" alt="Card image cap">
    {% endthumbnail %}
        <div class="card-body">
          <h5>{{ employer.position }}</h5>
          <p class='card-text'>{{ employer.name }}</h4>
          <p class='card-text'>{{ employer.description }}</p>
        </div>
        <div class="card-footer ">
          <small>Работает с {{ employer.work_since }}</small>
        </div>
      </div>
    {% endfor %}
  </div>
  </main>
{% endblock %}

lesovod/templates/includes/footer.html
<footer class="footer">
  <div id="footer">
    <p class="contact">ИНН/КПП:	1204003308/121801001 </p>
    <p class="contact">Тел: +7(902)-465-79-44</p>
    <p class="contact">
      Адрес: Республика Марий-Эл, Килемарский район, село Кумья, Сосновая д.1
    </p>
  </div>
  <div id="footer">
    <p class="trade_mark">
      <span style="color: red">© All Rights Reserved by</span>
      <a class="navbar-text" href="https://github.com/huli-net">Roman Losev</a>
    </p>
  </div>
</footer>

lesovod/templates/includes/header.html
<header class="header">
  {% load static %}
  <nav class="navbar justify-content-center">
    <a class="navbar-brand text" href="{% url 'index' %}">
      <img
        src="{% static 'icons/icon.png' %}"
        width="50"
        height="50"
        class="d-inline-block align-top"
        alt="Logo"
      />
    </a>
    <div class="container">
        <a class="navbar-text" href="{% url 'index' %}">Главная страница</a>
        <a class="navbar-text"  href="{% url 'posts' %}">Новости</a>
<!--        <a class="navbar-text"  href="{% url 'employers' %}">Сотрудники</a>-->
        <a class="navbar-text" href="{% url 'about' %}">О компании</a>
    {% if user.is_authenticated %}

    <a class="navbar-text" href="{% url 'new_post' %}">Новая запись</a>

    <a class="navbar-text" href="{% url 'users:logout' %}"> <span style="color:red"> {{ user.username }}</span></a>
    {% endif %}
</div>
<div class='overlay'>
  <h1 class='header-title'></h1>
</div>
    <!--<a href="{% url 'users:login' %}">Вход для сотрудников</a>-->
  </nav>
</header>

lesovod/templates/index.html
{% extends 'base.html' %}{% load static %} {% block content %}

<div class="welcome-box">
  <div class="welcome">
    <div class="welcome-info"><p class="info">Общая площадь во владении: 50000ГА</p></div>
    <div class="welcome-info"><p class="info">Площадь посадки: 15000ГА</p></div>
    <div class="welcome-info"><p class="info">Площадь охот-хозяйства: 15000ГА</p></div>
<!--    <div class="welcome-info"><p class="info">И т.д. и т.п.</p></div>-->
  </div>
</div>
{%endblock%}

lesovod/templates/new_post.html
{% extends 'base.html' %} {% block content %} {% load user_filters %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="card-post">
    <div class="card-header text-center label-post">
      {% if is_edit %} Редактирование поста {% else %} Новый пост {% endif %}
    </div>
    {% for field in form %}
    <div
      class="form-post"
      {% if field.field.required %}
      aria-required="true"
      {% else %}
      aria-required="false"
      {% endif %}
      >
      <label for="{{ field.id_for_label }}" class="label-post">
        {{ field.label }}
      </label>
      <div>
        {{ field|addclass:'form-control' }} {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
        {% endif %}
      </div>
    </div>
    {% endfor %}
  <div class="button-area">
    <button class="button-post" type="submit">Отправить</button> 
  </div>
  </div>
</form>
{% endblock %}

lesovod/templates/paginator.html

    {% if page_obj.has_other_pages %}
    <div class="paginator">
      {% if page_obj.has_previous %}
      <a class="a-paginator" href="?page={{ page_obj.previous_page_number }}">‹Предыдущая</a>
      {% endif %}
      {% for i in page_obj.paginator.page_range %}
            {% if page_obj.number == i %}
              <a class="a-paginator active">{{ i }}</a>
            {% else %}
              <a class="a-paginator" href="?page={{ i }}">{{ i }}</a>
            {% endif %}
      {% endfor %}
            {% if page_obj.has_next %}
              <a class="a-paginator" href="?page={{ page_obj.next_page_number }}">Следующая ›</a>
              <a class="a-paginator" href="?page={{ page_obj.paginator.num_pages }}">Последняя »</a>
            {% endif %}
    </div>
    {% endif %}

lesovod/templates/posts.html
{% extends 'base.html' %} {% load thumbnail %} {% block content %}
<main>
  {% include 'paginator.html' %}
  {% for post in page_obj %}
          <div class="card-wrapper">
            <div class="card-news">
                  {% thumbnail post.image "x480" as im %}
                  <img class='post-image' src="{{ im.url }}" />
                  {% endthumbnail %}
              <div class="text-box-wrapper">
              <div class="text-box">
                <h1 class="heading">
                  {{ post.title}}
                </h1>
               <p class="post-text">
                  {{ post.text}}
               </p>               
                <p class='pub_date'>
                 {{ post.pub_date }}
                </p>
               
              </div>
             </div>
            </div>
          </div>
  {% endfor %}
  {% include 'paginator.html' %}
  {% endblock %}

</main>

lesovod/templates/users/logged_out.html
{% extends 'base.html' %}
{% block title %}Вы вышли из системы{% endblock %}
{% block content %}
<div class="row justify-content-center">
  <div class="col-md-8 p-5">
    <div class="card">
      <div class="card-header">
        Выход
      </div>
      <div class="card-body">
        <p>
          Вы вышли из своей учётной записи. Ждём вас снова!
        </p>
      </div> <!-- card body -->
    </div> <!-- card -->
  </div> <!-- col -->
</div> <!-- row -->
{% endblock %} 

lesovod/templates/users/login.html
{% extends "base.html" %}
{% block title %}Войти{% endblock %}
{% block content %}
{% load user_filters %}
  <div class="row justify-content-center">
    <div class="col-md-8 p-5">
      <div class="card bg-dark text-white">
        <div class="card-header">
          Войти на сайт
        </div>
        <div class="card-body">
          {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}            
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
          {% endif %}

          <form method="post"
            {% if action_url %}
              action="{% url action_url %}"
            {% endif %}
          >
          {% csrf_token %}

          {% for field in form %}
            <div class="form-group row my-3"
              {% if field.field.required %} 
                aria-required="true"
              {% else %}
                aria-required="false"
              {% endif %}
            >
              <label for="{{ field.id_for_label }}">
                {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
              </label>
              <div>
              {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
            </div>
          {% endfor %}
          <div class="col-md-6 offset-md-4">
            <button type="submit" class="btn btn-primary">
              Войти
            </button>
          </div>
          </form>
        </div> 
      </div>
    </div> 
</div> 
{% endblock %} 